version: 2
jobs:
  build:
    working_directory: ~/circleci-coimporter
    docker:
      - image: circleci/python:3.6.4  # primary container for the build job
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout  # checkout source code to working directory
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - run:
          command: |  # use pipenv to install dependencies
            sudo pip install pipenv
            pipenv install
      - run:
        command: |
          pipenv run python -m unittest discover
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1
